/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package object_introduction;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import mojeFunkcie.ImplementationSupportFunction;

/**
 *
 * @author Phenom
 */
public class Our_UI extends javax.swing.JFrame {
    
    // GUI form private atributes
    School gui_created_school = null;
    final String GUI_SAVE_FILE_NAME = "gui_created_object.txt"; // constant contains location
    ImplementationSupportFunction supportFunctionOnGUI = new ImplementationSupportFunction(); // instantionate object responsible for saving located in package mojeFunkcie

    /**
     * Creates new form Our_UI
     */
    public Our_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        Save_popup_menu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Exit_from_popup_menu = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        Save_popup_menu.setText("Save");
        Save_popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_popup_menuActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Save_popup_menu);
        jPopupMenu2.add(jSeparator2);

        Exit_from_popup_menu.setText("Exit program");
        Exit_from_popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_from_popup_menuActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Exit_from_popup_menu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOP programming demo v. 1.0, 2021");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setComponentPopupMenu(jPopupMenu2);

        jLabel1.setText("School name:");
        jLabel1.setToolTipText("");

        jLabel2.setText("School type:");

        jLabel3.setText("Nr. of chasses:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Section for School object creation");

        jTextField3.setText("12");
        jTextField3.setToolTipText("");

        jButton1.setText("Create School object");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save School object");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Show School object");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Text output filed 1");

        jLabel6.setText("Text output filed 2");

        jLabel7.setText("Text output filed 3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Section for main message text");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/object_introduction/images/Presentation.png"))); // NOI18N
        jLabel9.setText("OOP programming tutorial");
        jLabel9.setToolTipText("Lnik for visiting project homepage cdesigner.eu.");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(94, 94, 94)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.getAccessibleContext().setAccessibleDescription("Go to project homepage cdesigner.eu.");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/object_introduction/images/Folder.png"))); // NOI18N
        jMenuItem1.setText("Create Obj School");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/object_introduction/images/small_Floppy Disk.png"))); // NOI18N
        jMenuItem2.setText("Save Object");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/object_introduction/images/Power.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/object_introduction/images/Information 3.png"))); // NOI18N
        jMenuItem3.setText("About OOP demo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: Create object School
        
        String schoolName = null, schoolType = null;
        
        // read from field
        if (jTextField1.getText() == "") {
            jLabel8.setText("Please fill school name!");  // main message text
        } else {
            schoolName = jTextField1.getText();
        }
        
        
        if (jTextField2.getText() == "") {
            jLabel8.setText("Please fill school type!");  // main message text
        } else {
            schoolType = jTextField2.getText();
        }
        
        int numberOfClasses = Integer.parseInt( jTextField3.getText());
        
        if ( (schoolName.isEmpty()) || (schoolType.isEmpty())) { // testing if it si not empty
            
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Please correct values entered into a text field!");  // main message text
            
        } else {
            
            
            gui_created_school = new School(schoolName, schoolType, numberOfClasses);
             // outputting text after scuccesfull object creation
            jLabel5.setText("School name is: " + schoolName);  // first line of mesage
            jLabel6.setText("School type: " + schoolType);  // second line of message
            jLabel7.setText("Number of classes is: " + numberOfClasses);  // third line of message
            jLabel8.setText("Object gui_created_school has been created!");  // main message text
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here: after form window opened
        jLabel5.setText("");  // first line of mesage
        jLabel6.setText("");  // second line of message
        jLabel7.setText("");  // third line of message
        jLabel8.setText("");  // main message text
        // hint for label9
        jLabel9.setToolTipText("Link to a project page cdesigner.eu.");
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:  here we save our object
        if (gui_created_school != null) { // object was created and is not empty
             if (supportFunctionOnGUI.saveObject(GUI_SAVE_FILE_NAME, gui_created_school)) { //
                 System.out.println("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);
                 jLabel8.setText("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);  // main message text
             } else {
                 System.out.println("There were errors during saving process!");
             } 
        
      
            
            
            
        } else { // object does not exist
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Object can not be saved beacause is empty, please create them first!");  // main message text
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: part responsible for reading and showing last saved object
        
        gui_created_school = (School)supportFunctionOnGUI.readObject(GUI_SAVE_FILE_NAME);
        System.out.println("Our restored school from file contains these data:");
        
        if (gui_created_school != null) { // object was created and is not empty
             jLabel5.setText("School name is: " + gui_created_school.getName());  // first line of mesage
            jLabel6.setText("School type: " + gui_created_school.getType());  // second line of message
            jLabel7.setText("Number of classes is: " + gui_created_school.getNrOfClasses());  // third line of message
            jLabel8.setText("We succesfully restored school named: "  + gui_created_school.getName());  // main message text  
            
            // restore texts into a text editation fields
            jTextField1.setText(gui_created_school.getName());
            jTextField2.setText(gui_created_school.getType());
            jTextField3.setText(String.valueOf(gui_created_school.getNrOfClasses()));
      
            
            
            
        } else { // object does not exist and cannot be deserialized
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Object can not be restored beacause is empty, please create them  and save first!");  // main message text
        }
        
        try {
           gui_created_school.showAllSchoolClasses(); // show content of restored school
        }
	catch(NullPointerException e) {
	   System.out.println("NullPointerException thrown!");
	}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here: Menu Exit - onclick
        System.exit(0); // terminate actual running virtual maschine
        // more about ending windows or programs can be obtained from here
        // https://stackoverflow.com/questions/8632705/how-to-close-a-gui-when-i-push-a-jbutton , 17.4.2021
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here: save from menu
         if (gui_created_school != null) { // object was created and is not empty
             if (supportFunctionOnGUI.saveObject(GUI_SAVE_FILE_NAME, gui_created_school)) { //
                 System.out.println("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);
                 jLabel8.setText("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);  // main message text
             } else {
                 System.out.println("There were errors during saving process!");
             } 
        
      
            
            
            
        } else { // object does not exist
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Object can not be saved beacause is empty, please create them first!");  // main message text
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here: Create object from menu
         String schoolName = null, schoolType = null;
        
        // read from field
        if (jTextField1.getText() == "") {
            jLabel8.setText("Please fill school name!");  // main message text
        } else {
            schoolName = jTextField1.getText();
        }
        
        
        if (jTextField2.getText() == "") {
            jLabel8.setText("Please fill school type!");  // main message text
        } else {
            schoolType = jTextField2.getText();
        }
        
        int numberOfClasses = Integer.parseInt( jTextField3.getText());
        
        if ( (schoolName.isEmpty()) || (schoolType.isEmpty())) { // testing if it si not empty
            
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Please correct values entered into a text field!");  // main message text
            
        } else {
            
            
            gui_created_school = new School(schoolName, schoolType, numberOfClasses);
             // outputting text after scuccesfull object creation
            jLabel5.setText("School name is: " + schoolName);  // first line of mesage
            jLabel6.setText("School type: " + schoolType);  // second line of message
            jLabel7.setText("Number of classes is: " + numberOfClasses);  // third line of message
            jLabel8.setText("Object gui_created_school has been created!");  // main message text
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here: About info from menu - we use dialog boxes or option pane
        // more about read from https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html , 17.4.2021
        JOptionPane.showMessageDialog(null,"OOP programming demo v 1.0. \n (c) cdesigner.eu, 2021");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here: Loading page after click on presentation icon on Label9
        try {
         
        Desktop.getDesktop().browse(new URI("http://www.cdesigner.eu"));
         
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void Save_popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_popup_menuActionPerformed
        // TODO add your handling code here: save from popup menu
        if (gui_created_school != null) { // object was created and is not empty
             if (supportFunctionOnGUI.saveObject(GUI_SAVE_FILE_NAME, gui_created_school)) { //
                 System.out.println("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);
                 jLabel8.setText("School object succcesfully saved to file named: " + GUI_SAVE_FILE_NAME);  // main message text
             } else {
                 System.out.println("There were errors during saving process!");
             } 
        
      
            
            
            
        } else { // object does not exist
            jLabel5.setText("");  // first line of mesage
            jLabel6.setText("");  // second line of message
            jLabel7.setText("");  // third line of message
            jLabel8.setText("Object can not be saved beacause is empty, please create them first!");  // main message text
        }
        
    }//GEN-LAST:event_Save_popup_menuActionPerformed

    private void Exit_from_popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_from_popup_menuActionPerformed
        // TODO add your handling code here: exit after selectin exit from popup menu
        System.exit(0); // terminate actual running virtual maschine
        // more about ending windows or programs can be obtained from here
        // https://stackoverflow.com/questions/8632705/how-to-close-a-gui-when-i-push-a-jbutton , 17.4.2021 implemented during tutorial shoot at 18.4.2021
    }//GEN-LAST:event_Exit_from_popup_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Our_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Our_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Our_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Our_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Our_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit_from_popup_menu;
    private javax.swing.JMenuItem Save_popup_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
